AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Instances with Launch Template, Docker and CodeDeploy Agent

Resources:

  # Security Group for EC2
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP
      VpcId: !ImportValue MyVPC-Id
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: InstanceSG

  # Launch Template with UserData script
  EC2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: DockerCodeDeployTemplate
      LaunchTemplateData:
        InstanceType: t3.micro
        ImageId: ami-0c02fb55956c7d316  # Amazon Linux 2 (Virginia)
        KeyName: Virginia-Compute
        SecurityGroupIds:
          - !Ref InstanceSecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y

            # نصب Docker
            amazon-linux-extras install docker -y
            service docker start
            usermod -a -G docker ec2-user

            # نصب CodeDeploy Agent
            yum install -y ruby
            cd /home/ec2-user
            wget https://aws-codedeploy-${AWS::Region}.s3.${AWS::Region}.amazonaws.com/latest/install
            chmod +x ./install
            ./install auto

            service codedeploy-agent start
            chkconfig codedeploy-agent on

  # EC2 Instance 1 using Launch Template
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref EC2LaunchTemplate
        Version: !GetAtt EC2LaunchTemplate.LatestVersionNumber
      SubnetId: !ImportValue PublicSubnet1Id
      Tags:
        - Key: Name
          Value: DockerInstance1
        - Key: Env
          Value: Prod
        - Key: Role
          Value: Frontend
        - Key: App
          Value: TodoApp

  # EC2 Instance 2 using Launch Template
  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref EC2LaunchTemplate
        Version: !GetAtt EC2LaunchTemplate.LatestVersionNumber
      SubnetId: !ImportValue PublicSubnet2Id
      Tags:
        - Key: Name
          Value: DockerInstance2
        - Key: Env
          Value: Prod
        - Key: Role
          Value: Frontend
        - Key: App
          Value: TodoApp
