AWSTemplateFormatVersion: '2010-09-09'
Description: >
  ECS Cluster and Service with CodeDeploy deployment controller (Blue/Green ready),
  including IAM Role for CodeDeploy and Security Group for ECS tasks.

Parameters:
  TaskDefinitionArn:
    Type: String
    Description: ARN of existing ECS Task Definition
  DesiredCount:
    Type: Number
    Default: 1
    Description: Number of desired ECS tasks

Resources:

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: my-ecs-cluster

  ECSServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP to ECS tasks
      VpcId: !ImportValue MyVPC-Id
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  CodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodeDeployServiceRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeDeployRoleForECS

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      ServiceName: my-ecs-service
      TaskDefinition: !Ref TaskDefinitionArn
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      DeploymentController:
        Type: CODE_DEPLOY
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref ECSServiceSecurityGroup
          Subnets:
            - !ImportValue PrivateSubnet1Id
            - !ImportValue PrivateSubnet2Id
      Role: !GetAtt CodeDeployServiceRole.Arn

Outputs:
  ClusterName:
    Description: ECS Cluster Name
    Value: !Ref ECSCluster
  ServiceName:
    Description: ECS Service Name
    Value: !Ref ECSService
  CodeDeployRoleArn:
    Description: IAM Role ARN for CodeDeploy
    Value: !GetAtt CodeDeployServiceRole.Arn
