name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  AWS_REGION: ${{ vars.AWS_REGION }} 
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy VPC Stack
        run: |
          aws cloudformation deploy \
            --template-file CloudFormation/01-Deploy-VPC.yml \
            --stack-name Deploy-VPC \
            --capabilities CAPABILITY_NAMED_IAM \
            --region ${{ env.AWS_REGION }}  

      - name: Deploy EC2 Instance Stack
        run: |
          aws cloudformation deploy \
            --template-file CloudFormation/02-01-Deploy-EC2-Instance.yml \
            --stack-name Deploy-EC2-DockerInstance \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides KeyName=class-key
            --region ${{ env.AWS_REGION }}  

      - name: Deploy Postgres Instance Stack
        run: |
          aws cloudformation deploy \
            --template-file CloudFormation/02-03-Deploy-EC2-PostgresInstance.yml \
            --stack-name Deploy-Postgres-DockerInstance \
            --capabilities CAPABILITY_NAMED_IAM \
            --region ${{ env.AWS_REGION }}  
